<a href="https://colab.research.google.com/github/KimYongHwi/ml_definitive_guide_study/blob/main/3%EC%9E%A5_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pandas
- 판다스는 파이썬에서 데이터 처리를 위해 존재하는 가장 있기 있는 라이브러리
- 일반적으로 대부분의 데이터 세트는 2차원 데이터로 행과 열로 구성돼 있다
- 행과 열로 이루어진 2차원 데이터를 효율적으로 가공/처리할 수 있는 다양하고 훌륭한 기능 제공

#### 주요 구성요소
- DataFrame: 행과 열을 가지고 있는 2차원 데이터셋 (index를 가지고 있음)
- Series: 1개의 열 값으로만 구성된 1차원 데이터셋

In [2]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import os
from pathlib import Path

In [4]:
folder = "ml_definitive_guide/data/titanic"

base_path = Path("/content/drive/My Drive/")
project_path = base_path / folder
os.chdir(project_path)

for x in list(project_path.glob("*")):
    if x.is_dir():
        dir_name = str(x.relative_to(project_path))
        os.rename(dir_name, dir_name.split(" ", 1)[0])

print(f"현재 디렉토리 위치: {os.getcwd()}")

현재 디렉토리 위치: /content/drive/My Drive/ml_definitive_guide/data/titanic


In [5]:
import pandas as pd

- read_scv를 이용하여 csv 파일을 편리하게 DataFrame으로 로딩

In [6]:
titanic_df = pd.read_csv('./train.csv')
print('titanic 변수 type:',type(titanic_df))

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>


- head를 이용하여 DataFrame의 맨 앞 일부 데이터만 추출

In [7]:
titanic_df.head(3)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S

[3 rows x 12 columns]

- DataFrame 생성

In [8]:
dic1 = {
    'Name': ['Chulmin', 'Enukyung', 'Jinwoong', 'Soobeom'],
    'Year': [2011, 2016, 2015, 2015],
    'Gender': ['Male', 'Female', 'Male', 'Male']
}

# 딕셔너리를 DataFrame으로 변환
data_df = pd.DataFrame(dic1)
print(data_df)
print('#' * 30)

# 새로운 컬럼명을 추가
data_df = pd.DataFrame(dic1, columns=['Name', 'Year', "Gender", 'Age'])
print(data_df)
print('#' * 30)

# 인덱스를 새로운 값으로 할당
data_df = pd.DataFrame(dic1, index=['one', 'two', 'three', 'four'])
print(data_df)
print('#' * 30)

       Name  Year  Gender
0   Chulmin  2011    Male
1  Enukyung  2016  Female
2  Jinwoong  2015    Male
3   Soobeom  2015    Male
##############################
       Name  Year  Gender  Age
0   Chulmin  2011    Male  NaN
1  Enukyung  2016  Female  NaN
2  Jinwoong  2015    Male  NaN
3   Soobeom  2015    Male  NaN
##############################
           Name  Year  Gender
one     Chulmin  2011    Male
two    Enukyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male
##############################


- DataFrame의 컬럼명과 인덱스

In [9]:
print('columns:', titanic_df.columns)
print('index:', titanic_df.index)
print('index value:', titanic_df.index.values[0:3])

columns: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
index: RangeIndex(start=0, stop=891, step=1)
index value: [0 1 2]


- DataFrame에서 Series 추출 및 DataFrame 필터링 추출

In [10]:
# DataFrame 객체에서 []연산자내에 한개의 컬럼만 입력하면 Series 객체를 반환
series = titanic_df['Name']
print(series.head(3))
print('## type:', type(series))

# DataFrame객체에서 []연산자내에 여러개의 컬럼을 리스트로 입력하면 그 컬럼들로 구성된 DataFrame 반환
filtered_df = titanic_df[['Name', 'Age']]
print(filtered_df.head(3))
print('## type:', type(filtered_df))

# DataFrame객체에서 []연산자내에 한개의 컬럼을 리스트로 입력하면 한캐의 컬럼으로 구성된 DataFrame 반환
one_col_df = titanic_df[['Name']]
print(one_col_df.head(3))
print('## type:', type(one_col_df))



0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
Name: Name, dtype: object
## type: <class 'pandas.core.series.Series'>
                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
## type: <class 'pandas.core.frame.DataFrame'>
                                                Name
0                            Braund, Mr. Owen Harris
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
## type: <class 'pandas.core.frame.DataFrame'>


- shape

In [11]:
print('DataFrame 크기:', titanic_df.shape)

DataFrame 크기: (891, 12)


- info: DataFrame내의 컬럼명, 데이터 타입, Null건수, 데이터 건수 정보를 제공

In [12]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


- describe: 데이터들의 평균, 표준편차, 4분위 분포도를 제공(숫자형 컬럼들에 대해서 해당 정보를 제공)

In [13]:
titanic_df.describe()

PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  ...  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642  ...    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071  ...    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000  ...    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000  ...    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000  ...    8.000000    6.000000  512.329200

[8 rows x 7 columns]

- value_counts
  - 동일한 개별 데이터 값이 몇건이 있는지 정보를 제공
  - 개별 데이터값의 분포도를 제공
  - Series 객체에서만 호출 될 수 있으므로 반드시 DataFrame을 단일 컬럼으로 입력하여 Series로 변환한 뒤 호출
  

In [14]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts.sort_index())

<class 'pandas.core.series.Series'>
1    216
2    184
3    491
Name: Pclass, dtype: int64


In [15]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [16]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

- sort_values() by=정렬컬럼, ascending=True 또는 False로 오름차순/내림차순으로 정렬

In [17]:
titanic_df.sort_values(by='Pclass', ascending=True)

titanic_df[['Name', 'Age']].sort_values(by='Age')
titanic_df[['Name', 'Age', 'Pclass']].sort_values(by=['Pclass', 'Age'])

Name    Age  Pclass
305            Allison, Master. Hudson Trevor   0.92       1
297              Allison, Miss. Helen Loraine   2.00       1
445                 Dodge, Master. Washington   4.00       1
802       Carter, Master. William Thornton II  11.00       1
435                 Carter, Miss. Lucile Polk  14.00       1
..                                        ...    ...     ...
859                          Razi, Mr. Raihed    NaN       3
863         Sage, Miss. Dorothy Edith "Dolly"    NaN       3
868               van Melkebeke, Mr. Philemon    NaN       3
878                        Laleff, Mr. Kristo    NaN       3
888  Johnston, Miss. Catherine Helen "Carrie"    NaN       3

[891 rows x 3 columns]

### DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

- 리스트, ndarray에서 DataFrame 변환

In [18]:
import numpy as np

col_name1 = ['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)

print('array1 shape:',array1.shape)
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [19]:
col_name2 = ['col1', 'col2', 'col3']

list2 = [[1, 2, 3],
         [11, 12, 13]]

array2 = np.array(list2)
print('array2 shape:', array2.shape)
df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


- dict에서 DataFrame 변환

In [20]:
dict = { 'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33] }
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


- DataFrame을 ndarray로 변환

In [21]:
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


- DataFrame을 리스트와 딕셔너리로 변환

In [22]:
# DataFrame을 리스트로 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist 타입:', type(list3))
print(list3)

# DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list') # value를 리스트로 반환
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3) 
print(df_dict.to_dict()) # value를 dict로 반환

df_dict.values.tolist 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}
{'col1': {0: 1, 1: 11}, 'col2': {0: 2, 1: 22}, 'col3': {0: 3, 1: 33}}


### DataFrame의 컬럼 데이터 셋 Access
- DataFrame의 컬럼 데이터셋 생성과 수정은 `[]`연산자를 이용해 쉽게 할 수 있다.
- 새로운 컬럼에 값을 할당하려면 DataFrame[] 내에 새로운 컬럼명을 입력하고 값을 할당하면 된다.

In [23]:
titanic_df['Age_0'] = 0
titanic_df.head(3)

PassengerId  Survived  Pclass  ... Cabin Embarked  Age_0
0            1         0       3  ...   NaN        S      0
1            2         1       1  ...   C85        C      0
2            3         1       3  ...   NaN        S      0

[3 rows x 13 columns]

In [24]:
titanic_df['Age_by_10'] = titanic_df['Age'] * 10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

PassengerId  Survived  Pclass  ... Age_0 Age_by_10  Family_No
0            1         0       3  ...     0     220.0          2
1            2         1       1  ...     0     380.0          2
2            3         1       3  ...     0     260.0          1

[3 rows x 15 columns]

- 기존 컬럼에 값을 업데이트 하려면 해당 컬럼에 업데이트값을 그대로 지정하면 된다.

In [25]:
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

PassengerId  Survived  Pclass  ... Age_0 Age_by_10  Family_No
0            1         0       3  ...     0     320.0          2
1            2         1       1  ...     0     480.0          2
2            3         1       3  ...     0     360.0          1

[3 rows x 15 columns]

#### DataFrame의 drop()
- axis: DataFrame의 행을 삭제할 때는 axis = 0, 열을 삭제할 때는 axis = 1로 설정
- 원본 DataFrame은 유지하고 드롭된 DataFrame을 새롭게 객체 변수로 받고 싶다면 inplace=False로 설정(default: False)
  - ex: `titanic_drop_df = titanic_df.drop('Age_0', axis=1, inplace=False)`
- 원본 DataFrame에 드롭된 결과를 적용할 경우에는 inplace=True를 적용
  - ex: `titanic_df.drop('Age_0', axis=1, inplace=True)`
- 원본 DataFrame에서 드롭된 DataFrame을 다시 원본 DataFrame 객체 변수로 할당하면 원본 DataFrame에서 드롭된 결과를 적용할 경우와 같은
  - ex: `titanic_df = titanic_df.drop('Age_0', axis=1, inplace=False)`

- axis에 따른 삭제

In [26]:
# drop() 메소드의 inplace 기본값이 False
# drop()을 호출한 DataFrame은 아무런 영향이 없으며 drop()호출의 결과가 해당 컬럼이 drop된 DataFrame을 반환한다
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
display(titanic_drop_df.head(3))
print()
print('#' * 130)
print()
display(titanic_df.head(3))

PassengerId  Survived  Pclass  ... Embarked Age_by_10  Family_No
0            1         0       3  ...        S     320.0          2
1            2         1       1  ...        C     480.0          2
2            3         1       3  ...        S     360.0          1

[3 rows x 14 columns]


##################################################################################################################################



PassengerId  Survived  Pclass  ... Age_0 Age_by_10  Family_No
0            1         0       3  ...     0     320.0          2
1            2         1       1  ...     0     480.0          2
2            3         1       3  ...     0     360.0          1

[3 rows x 15 columns]

- 여러개의 컬럼을 삭제할 때는 drop의 인자로 삭제할 컬럼 리스트를 입력한다.
- `inplace=True`일 경우 호출한 DataFrame에 drop이 반영된다. (반환값은 None)

In [27]:
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print('inplace=True로 drop 후 반환된 값:', drop_result)
titanic_df.head(3)

inplace=True로 drop 후 반환된 값: None


PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S

[3 rows x 12 columns]

- axis=0일 경우 drop은 row 방향으로 데이터를 삭제한다.

In [28]:
titanic_df = pd.read_csv('./train.csv')
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('##### before axis 0 drop #####')
print(titanic_df.head(6))

titanic_df.drop([0,1,2], axis=0, inplace=True)

print('##### after axis 0 drop #####')
print(titanic_df.head(3))

##### before axis 0 drop #####
   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q

[6 rows x 12 columns]
##### after axis 0 drop #####
   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q

[3 rows x 12 columns]


### Index
- 판다스의 Index 객체는 RDBMS의 PK와 유사하게 DataFrame, Series의 레코드를 고유하게 식별하는 객체이다.
- DataFrame, Series에서 Index 객체만 추출하려면 `DataFrame.index` 또는 `Series.index` 속성을 통해 가능하다.
- Series 객체는 Index 객체를 포함하지만 Series 객체에 연산 함수를 적용할 때 Index는 연산에서 제외된다.
- DataFrame 및 Series에 reset_index()메소드를 수행하면 새롭게 인덱스를 연속 숫자형으로 할당하며 기존 인덱스는 'index'라는 새로운 컬럼 명으로 추가한다.

In [29]:
titanic_df = pd.read_csv('./train.csv')
indexes = titanic_df.index
print(indexes)
print('Index 객체 array값:\n', indexes.values[0:3])

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [0 1 2]


- index는 1차원 데이터이다.

In [30]:
print(type(indexes))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'pandas.core.indexes.range.RangeIndex'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


- []를 이용하여 index의 값을 변경할 수 없다.

In [31]:
indexes[0] = 5

TypeError: ignored

- Series 객체는 Index 객체를 포함하지만 Series 객체에 연산 함수를 적용할 때 Index는 연산에서 제외된다.
- Index는 오직 식별용으로만 사용된다.

In [ ]:
series_fare = titanic_df['Fare']
series_fare.head(5)

In [ ]:
print('Fare Series max 값:', series_fare.max())
print('Fare Series sum 값:', series_fare.sum())
print('sum() Fare Series:', sum(series_fare))
print('Fare Series + 3:\n',(series_fare + 3).head(3) )

- DataFrame 및 Series에 reset_index() 메소드를 수행하면 새롭게 인덱스를 연속 숫자 형으로 할당하며 기존 인덱스는 'index'라는 새로운 컬럼명으로 추가한다.

In [ ]:
titanic_reset_df = titanic_df.reset_index()
titanic_reset_df.head(3)

In [ ]:
titanic_reset_df.shape

In [ ]:
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:',type(value_counts))

new_value_counts = value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:',type(new_value_counts))

### 데이터 셀렉션 및 필터링
- []: 컬럼 기반 필터링 또는 boolean 인덱싱 필터링 제공
- ix[], loc[], ilov[]: 명칭/위치 기반 인덱싱 제공
- Boolean 인덱싱: 조건식에 따른 필터링을 제공

In [ ]:
titanic_df = pd.read_csv('./train.csv')
print('단일 컬럼 데이터 추출:\n', titanic_df['Pclass'].head(3))
print('\n여러 컬럼들의 데이터 추출:\n', titanic_df[['Survived', 'Pclass']].head(3))
# print('[ ] 안에 숫자 index는 KeyError 오류 발생:\n', titanic_df[0])

- 앞에서 DataFrame의 [ ] 내에 숫자 값을 입력할 경우 오류가 발생한다고 했는데, Pandas의 Index 형태로 변환 가능한 표현식은 [ ] 내에 입력할 수 있다.

In [ ]:
titanic_df[0:2]

- [] 내에 조건식을 입력하여 블린 인덱싱을 수행할 수 있다 (DataFrame 바로 뒤에 있는 []안에 들어갈 수 있는 것은 컬럼명과 블린인덱싱으로 범위를 좁혀서 작업하는데 도움이 된다.)

In [ ]:
titanic_df[titanic_df['Pclass'] == 3].head(3)

#### ix, loc, iloc
- 명칭 기반 인덱싱은 컬럼의 명칭을 기반으로 위치를 지정하는 방식이다.
- 컬럼 명 같이 명칭으로 열 위치를 지정하는 방식이다
- 위치 기반 인덱싱은 0을 출발점으로 하는 가로축, 세로축 좌표 기반의 행과 열 위치를 기반으로 데이터를 지정한다. 따라서 행, 열 위치값으로 정수가 입력된다.
- ix[]: 명칭 기반과 위치 기반 인덱싱을 함께 제공 (사라짐)
- loc[]: 명칭 기반 인덱싱
- iloc[]: 위치 기반 인덱싱


In [ ]:
data = {
    'Gender': ['Male', 'Female', 'Male', 'Male'],
    'Name': ['Chulmin', 'Eunkyung','Jinwoong','Soobeom'],
    'Year': [2011, 2016, 2015, 2015]
}

data_df = pd.DataFrame(data, index = ['one', 'two', 'three', 'four'])
data_df

In [ ]:
# data_df를 reset_index()로 새로운 숫자형 인덱스 생성
data_df_reset = data_df.reset_index()
data_df_reset = data_df_reset.rename(columns={'index': 'old_index'})

# index값에 1을 더해서 1부터 시작하는 새로운 index값 생성
data_df_reset.index = data_df_reset.index + 1
data_df_reset

- iloc: 위치기반 인덱싱 제공

In [ ]:
data_df

In [ ]:
data_df.iloc[0, 0]

In [ ]:
data_df.iloc[0, 'Name'] # 에러 발생

In [ ]:
data_df_reset.iloc[0, 1]

- loc: 명칭기반 인덱싱 제공

In [ ]:
data_df.loc['one', 'Name']

In [ ]:
data_df_reset

In [ ]:
data_df_reset.loc[1, 'Name']

In [ ]:
print('위치기반 iloc slicing\n', data_df.iloc[0:1, 0],'\n')
print('명칭기반 loc slicing\n', data_df.loc['one':'two', 'Name'])

In [ ]:
data_df_reset.loc[1:2, 'Name']

### Boolean indexing
- 위치기반, 명칭기반 인덱싱 모두 사용할 필요없이 조건식을 []기입하여 간편하게 필터링

In [ ]:
titanic_boolean = titanic_df[titanic_df['Age'] > 60]
print(type(titanic_boolean))
titanic_boolean.head(3)

In [ ]:
titanic_df['Age'] > 60

var1 = titanic_df['Age'] > 60
print(type(var1)) # Boolean Seriese 객체

In [ ]:
titanic_df[titanic_df['Age'] > 60][['Name', 'Age']].head(3)

In [ ]:
titanic_df[['Name', 'Age']][titanic_df['Age'] > 60].head(3)

In [ ]:
titanic_df.loc[titanic_df['Age'] > 60, ['Name', 'Age']].head(3)

- 논리 연산자로 결합된 조건식도 불린 인덱싱으로 적용 가능하다

In [ ]:
titanic_df[ (titanic_df['Age'] > 60) & (titanic_df['Pclass']==1) & (titanic_df['Sex'] == 'female')].head(3)

- 조건식은 변수로 할당 가능하다

In [ ]:
cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass'] == 1
cond3 = titanic_df['Sex'] == 'female'

titanic_df[ cond1 & cond2 & cond3 ]

### Aggregation 함수
- sum, max, min, count 등의 함수는 DataFrame/Series에서 집합(Aggregation) 연산을 수행
- DataFrame의 경우 DataFrame에서 바로 aggregation을 호출할 경우 모든 컬럼에 해당 aggregation을 적용
- Aggregation 함수 호출 시 axis값을 명시하지 않으면 axis=0(**행축 방향**)과 같은 결과 출력

In [33]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

- 특정 컬럼들로 Aggregation 메소드 수행

In [35]:
titanic_df[['Age', 'Fare']].mean(axis=1)

0      14.62500
1      54.64165
2      16.96250
3      44.05000
4      21.52500
         ...   
886    20.00000
887    24.50000
888    23.45000
889    28.00000
890    19.87500
Length: 891, dtype: float64

In [51]:
titanic_df[['Age', 'Fare']].mean(axis=0)

Age     29.699118
Fare    32.204208
dtype: float64

In [38]:
titanic_df[['Age', 'Fare']].count()

Age     714
Fare    891
dtype: int64

### Group By
- DataFrame은 Group by 연산을 위해 groupby() 메소드를 제공
- groupby() 메소드는 by 인자로 group by 하려는 컬럼명을 입력 받으면 DataFrameGroupBy 객체를 반환
- 이렇게 반환된 DataFrameGroupBy 객체에 aggregation 함수를 수행

In [39]:
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))
print(titanic_groupby)

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


- DataFrameGroupBy객체에 Aggregation 메소드를 호출하여 Group by 수행

In [40]:
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

PassengerId  Survived  Name  Sex  ...  Ticket  Fare  Cabin  Embarked
Pclass                                    ...                               
1               216       216   216  216  ...     216   216    176       214
2               184       184   184  184  ...     184   184     16       184
3               491       491   491  491  ...     491   491     12       491

[3 rows x 11 columns]

In [41]:
print(type(titanic_groupby))
print(titanic_groupby.shape)
print(titanic_groupby.index)

<class 'pandas.core.frame.DataFrame'>
(3, 11)
Int64Index([1, 2, 3], dtype='int64', name='Pclass')


In [43]:
titanic_groupby = titanic_df.groupby(by='Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby


PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [44]:
titanic_df[['Pclass', 'PassengerId', 'Survived']].groupby('Pclass').count()

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [45]:
titanic_df.groupby('Pclass')['Pclass'].count()

Pclass
1    216
2    184
3    491
Name: Pclass, dtype: int64

In [47]:
titanic_df['Pclass'].value_counts().sort_index()

1    216
2    184
3    491
Name: Pclass, dtype: int64

- Pandas는 여러개의 aggregation 함수를 적용할 수 있도록 agg() 함수를 제공

In [48]:
titanic_df.groupby('Pclass')['Age'].agg([max, min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

- 딕셔너리를 이용하여 다양한 aggregation 메소드를 적용

In [49]:
agg_format = {'Age': 'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

### 결손 데이터 처리하기
- isna(): DataFrame의 isna() 메소드는 주어진 컬럼값들이 NaN인지 여부를 True/False값으로 반환한다.(NaN이면 True)
- fillna(): Missing 데이터를 인자로 주어진 갑스로 대체한다.

In [52]:
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name  ...  Ticket   Fare  Cabin  Embarked
0        False     False   False  False  ...   False  False   True     False
1        False     False   False  False  ...   False  False  False     False
2        False     False   False  False  ...   False  False   True     False

[3 rows x 12 columns]

- isna() 반환 결과에 sum()을 호출하여 컬럼별로 NaN 건수를 구할 수 있다.

In [53]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

- fillna로 Missing 데이터 대체하기

In [54]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500  C000         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250  C000         S

[3 rows x 12 columns]

In [55]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64