<a href="https://colab.research.google.com/github/KimYongHwi/ml_definitive_guide_study/blob/main/4_2%EC%9E%A5_scikit_learn_%EC%A3%BC%EC%9A%94API_%EB%AA%A8%EB%93%88_%EB%B0%8F_%EB%82%B4%EC%9E%A5_%EC%98%88%EC%A0%9C_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%85%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn의 Estimator와 fit(), predict()
- Estimator
  - 분류(Classifier)
    - DecisionTressClassifier
    - RandomForestClassifier
    - GradientBoostingClassifier
    - GaussianNB
    - SVC
  - 회귀(Regressor)
    - LinearRegression
    - Ridge
    - Lasso
    - RandomForestRegressor
    - GradientBoostingRegressor

### scikit-learn 주요 모듈
- datasets
 - `sklearn.datasets`: 사이킷런에 내장된 예제 데이터셋
- model_selection
 - `sklearn.model_selection`: 데이버 분리, 검증, 파라미터 튜닝등의 API 제공
- feature_engineering
  - `sklearn.preprocessiong`: 데이터 전처리에 필요한 다양한 기능 제공 (문자열 인코딩, 정규화, 스케일링 등)
  - `sklearn.feature_selection`: 알고리즘에 큰 평향을 미치는 피처를 우선순위 대로 셀렉션 작업을 수행하는 다양한 기능 제공
  - `sklearn.feature_extraction`: 텍스트 데이터나 이미지 데이터의 벡터화된 피처를 추출하는데 사용됨
- 차원 축소
  - `sklearn.decomposition`: 차원 축소와 관련한 알고리즘을 지원하는 모듈
- 평가
  - `sklearn.metrics`: 분류, 회귀, 클러스터링, 페어와이즈에 대한 다양한 성능 측정 방법 제공
- ML 알고리즘
  - `sklearn.ensemble`: 앙상블 알고리즘 제공
  - `sklearn.linear_model`: 주로 선형 회귀, 릿지(Ridge), 라쏘(Lasso) 및 로지스틱 회귀 등 회귀 관련 알고리즘 지원
  - `sklearn.navie_bayes`:  나이브 베이즈 알고리즘 제공
  - `sklearn.neighbors`: 최근접 이웃 알고리즘 제공
  - `sklearn.svm`: 서포트 벡터 머신 알고리즘 제공
  - `sklearn.tree`: 의사 결정 트리 알고리즘 제공
  - `sklearn.cluster`: 비지도 클러스터링 알고리즘 제공
- 유틸리티
  - `sklearn.pipeline`: 피처 처리 등의 변호나과 ML 알고리즘 학습, 예측 등을 함께 묶어서 실행할 수 있는 유틸리티 제공


### 내장 예제 데이터 셋 구성
- data: 데이터 셋
- target: 분류 시 레이블 값, 회귀 시 결과 값
- target_names: 개별 레이블의 이름
- feature_names: 피처의 이름
- DESCR: 데이터 세트에 대한 설명과 각 피처의 설명



In [3]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [5]:
keys = iris_data.keys()
print('붓꽃 데이터 셋의 keys:', keys)

붓꽃 데이터 셋의 keys: dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [7]:
print('feature_names 의 type:',type(iris_data.feature_names))
print('feature_names 의 shape:',len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names 의 type:',type(iris_data.target_names))
print(' feature_names 의 shape:',len(iris_data.target_names))
print(iris_data.target_names)

print('\n data 의 type:',type(iris_data.data))
print(' data 의 shape:',iris_data.data.shape)
print(iris_data['data'])

print('\n target 의 type:',type(iris_data.target))
print(' target 의 shape:',iris_data.target.shape)
print(iris_data.target)

feature_names 의 type: <class 'list'>
feature_names 의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names 의 type: <class 'numpy.ndarray'>
 feature_names 의 shape: 3
['setosa' 'versicolor' 'virginica']

 data 의 type: <class 'numpy.ndarray'>
 data 의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]